/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import model.User;
import dao.userdao;
import javax.swing.JOptionPane;
/**
 *
 * @author visha
 */
public class Register_Page extends javax.swing.JFrame {
    
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    /**
     * Creates new form Register_Page
     */
    public Register_Page() {
        initComponents();
        btnRegister.setEnabled(false);
//        txtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Male", "Female", "Other"}));
    }
    public void RESET(){
        txtFullname.setText("");
        txtage.setText("");
        txtemail.setText("");
        txtpassword.setText("");
        String gender = " ";
        if(rbMale.isSelected()){
            gender = "Male";
        }
        else if(rbFemale.isSelected()){
            gender = "Female";
        }
        else{
            gender = "Other";
        }
        
        btnRegister.setEnabled(false);
    }
    public void validateFields(){
        String name = txtFullname.getText();
        String age = txtage.getText();
        String email = txtemail.getText();
        String password = txtpassword.getText();
        String gender = " ";
        if(rbMale.isSelected()){
            gender = "Male";
        }
        else if(rbFemale.isSelected()){
            gender = "Female";
        }
        else{
            gender = "Other";
        }
        
        System.out.println("Fill All Details");
        System.out.println("Name empty" + name.equals(""));
        System.out.println("age empty" + age.equals(""));
        System.out.println("email empty" + email.equals(""));
        System.out.println("password empty" + password.equals(""));
        if(!name.equals("") && email.matches(emailPattern) && !password.equals("")){
            btnRegister.setEnabled(true);
        }
        else{
            btnRegister.setEnabled(false);
        }
        
//        if(name.isEmpty() || email.isEmpty() || password.isEmpty() || gender.isEmpty() || age <= 0){
//            JOptionPane.showMessageDialog(this, "All Field are Required");
//            return;
//        }
//        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtFullName = new javax.swing.JLabel();
        txtAge = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtPassword = new javax.swing.JLabel();
        txtGender = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        rbOther = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("SIGNUP");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 19, 128, 36));

        btnlogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        btnlogin.setText("Login ?");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel4.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 307, -1, -1));

        btnExit.setBackground(new java.awt.Color(255, 102, 102));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel4.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 308, 93, -1));

        txtFullName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtFullName.setForeground(new java.awt.Color(255, 0, 102));
        txtFullName.setText("Full Name");
        jPanel4.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtAge.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtAge.setForeground(new java.awt.Color(255, 0, 102));
        txtAge.setText("Age");
        jPanel4.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 0, 102));
        txtEmail.setText("Email");
        jPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        txtPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 0, 102));
        txtPassword.setText("Password");
        jPanel4.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtGender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtGender.setForeground(new java.awt.Color(255, 0, 102));
        txtGender.setText("Gender");
        jPanel4.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        txtFullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFullnameKeyReleased(evt);
            }
        });
        jPanel4.add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 66, 250, -1));

        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtageKeyReleased(evt);
            }
        });
        jPanel4.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 104, 250, -1));

        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });
        jPanel4.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 142, 250, -1));

        btnRegister.setBackground(new java.awt.Color(102, 102, 255));
        btnRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 272, -1, -1));

        btnReset.setBackground(new java.awt.Color(102, 102, 255));
        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 272, -1, -1));

        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
        });
        jPanel4.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 180, 250, -1));

        buttonGroup1.add(rbMale);
        rbMale.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        rbMale.setText("MALE");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });
        rbMale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rbMaleKeyReleased(evt);
            }
        });
        jPanel4.add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 217, -1, -1));

        buttonGroup1.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        rbFemale.setText("FEMALE");
        rbFemale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rbFemaleKeyReleased(evt);
            }
        });
        jPanel4.add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 217, -1, -1));

        buttonGroup1.add(rbOther);
        rbOther.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        rbOther.setText("OTHER");
        rbOther.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rbOtherKeyReleased(evt);
            }
        });
        jPanel4.add(rbOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 217, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_fitness - Copy.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 370));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 510, 370));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_fitness - Copy.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
int a = JOptionPane.showConfirmDialog(null, "Do You Really Want to close Apllication ", "Select", JOptionPane.YES_NO_OPTION);
if(a == 0)
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
Login_page s1 = new Login_page();
s1.show();// TODO add your handling code here:
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
User users = new User();
users.setName(txtFullname.getText());
users.setAge(Integer.parseInt(txtage.getText()));
users.setEmail(txtemail.getText());
users.setPassword(txtpassword.getText());
users.setGender(txtGender.getText());
userdao.REGISTER(users);
RESET();

if(users == null){
    JOptionPane.showMessageDialog(null, "<html><b style = \"colot:red\">Fill All Details <b></html>","Message", JOptionPane.ERROR_MESSAGE);
}else {
    setVisible(false);
    
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
RESET();        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtFullnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullnameKeyReleased
validateFields();        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullnameKeyReleased

    private void txtageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyReleased
validateFields();        // TODO add your handling code here:
    }//GEN-LAST:event_txtageKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
  validateFields();      // TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased
     validateFields();   // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordKeyReleased

    private void rbMaleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbMaleKeyReleased
       validateFields(); // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleKeyReleased

    private void rbFemaleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbFemaleKeyReleased
     validateFields(); // TODO add your handling code here:
    }//GEN-LAST:event_rbFemaleKeyReleased

    private void rbOtherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbOtherKeyReleased
    validateFields();   // TODO add your handling code here:
    }//GEN-LAST:event_rbOtherKeyReleased

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnlogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JRadioButton rbOther;
    private javax.swing.JLabel txtAge;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFullName;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
